checkout/urls.py
from . import views
from django.urls import path

app_name = "checkout"

urlpatterns = [
    path('delivery-choices/', views.delivery_choices, name='delivery-choices'),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"), 
    path("auth-handler/", views.checkout_handler, name='auth-handler'),
    path("address/checkout/", views.noAuthCheckoutView, name='no-auth-checkout'),
    #payment 
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),

]

ecom_core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('order.urls', namespace='orders')),
    path('dashboard/', include('services.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^download/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('get-order/', views.getOrder, name='get-order'),
    path('track-order/', views.orderTrackingView, name='track-order'),
]

store/urls.py
from . import views
from django.urls import path


app_name = "store"

urlpatterns = [
    #store urls
    path('', views.home, name='home'),
    path('product-detail/<uuid:product_url>/', views.product_detail, name='product-detail'),
    path('shop/', views.shopView, name='shop'),
    path('category/<slug:category_slug>/', views.product_category, name='category-list'),
    path('search/', views.searchView, name='search'),

    #blog urls
    path('blog-list/', views.BlogListView.as_view(), name='blog-list'),
    path('blog/<slug:slug>/', views.BlogPostDetailView.as_view(), name='blog-detail'),
    path('blog/filter=/<slug:blog_slug>', views.BlogListCategoryView.as_view(), name='blog-category-list'),

    #contact
    path('contact/', views.contactView, name='contact'),
]

store/forms.py
from django import forms 


class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Your Name'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class':'form-control', 'placeholder':'Email Address'}
        )
    )
    subject = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder':'What\'s this about?'}
        )
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'class':'form-control', 'rows':4, 'placeholder':'Your message....'})
    )

checkout/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from order.models import Order, OrderItem, AnonymousUser
from order.forms import AnonymousOrderSearchForm
from store.models import Product
from accounts.models import Address
from basket.basket import Basket

from .models import DeliveryOptions
from .forms import NoAuthCheckoutForm

# Create your views here.

'''
View to output the delivery options
'''
@login_required
def delivery_choices(request):
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    context = {
        "deliveryoptions": deliveryoptions,
    }

    return render(request, "checkout/delivery_choices.html", context)


''' 
This function will fire once a delivery option has been selected 
via AJAX which is implemeted in the cart.html template,
It will then modify the session and add the delivery price to the 
session and return a JSON response to the frontend.
'''
def basket_update_delivery(request):
    basket = Basket(request)
    if request.POST.get("action") == "post":
        delivery_option = int(request.POST.get("deliveryoption"))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = basket.basket_update_delivery(delivery_type.delivery_price)
        session = request.session
        if "purchase" not in request.session:
            session["purchase"] = {
                "delivery_id": delivery_type.id,
            }
        else:
            session["purchase"]["delivery_id"] = delivery_type.id
            session.modified = True
        response = JsonResponse({"total": str(updated_total_price), "delivery_price": str(delivery_type.delivery_price)})
        return response
    

def checkout_handler(request):
    if request.user.is_authenticated:
        return redirect('checkout:delivery_address')
    else:
        return redirect('checkout:no-auth-checkout')


def noAuthCheckoutView(request):
    session = request.session
    if "purchase" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])
    
    if request.method == "POST":
        form = NoAuthCheckoutForm(request.POST) 
        if form.is_valid():
            session['anonymous_user'] = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email'],
                'phone_number': form.cleaned_data['phone_number'],
                'district_or_city': form.cleaned_data['district_or_city'],
                'street_address': form.cleaned_data['street_address'],
                'other_address': form.cleaned_data['other_address'],
                'additional_notes': form.cleaned_data['additional_notes'],
            }
            return redirect('checkout:payment_selection')
    else:
        if 'anonymous_user' in session:
            form = NoAuthCheckoutForm(
                initial={
                    'first_name': session['anonymous_user']['first_name'],
                    'last_name': session['anonymous_user']['last_name'],
                    'email': session['anonymous_user']['email'],
                    'phone_number': session['anonymous_user']['phone_number'],
                    'district_or_city': session['anonymous_user']['district_or_city'],
                    'street_address': session['anonymous_user']['street_address'],
                    'other_address': session['anonymous_user']['other_address'],
                    'additional_notes': session['anonymous_user']['additional_notes'],
                }
            )
        else:   
            form = NoAuthCheckoutForm()
    context = {
        'form': form,
    }
    return render(request, 'checkout/no-auth-checkout.html', context)


@login_required(redirect_field_name='checkout:delivery_address', login_url='accounts:accounts-login')
def delivery_address(request):

    session = request.session
    if "purchase" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

    addresses = Address.objects.filter(customer=request.user).order_by("-default")
    if not addresses:
        messages.success(request, "Please add an address before you checkout")
        return redirect('accounts:add_address')

    if "address" not in request.session:
        session["address"] = {"address_id": str(addresses[0].id)}
    else:
        session["address"]["address_id"] = str(addresses[0].id)
        session.modified = True
    
    context = {"addresses": addresses}

    return render(request, "checkout/checkout.html", context)


def payment_selection(request):
    address = None
    if request.user.is_authenticated:
        address = Address.objects.filter(customer=request.user).order_by("-default")
        if "address" not in request.session:
            messages.success(request, "Please select address option")
            return HttpResponseRedirect(request.META["HTTP_REFERER"])
    else:
        address = request.session['anonymous_user']

    return render(request, "checkout/payment.html", {"addresses": address})

#pay pal 



def payment_complete(request):
    session = request.session
    body = json.loads(request.body)
    basket = Basket(request)
    delivery_option = get_object_or_404(DeliveryOptions, pk=session["purchase"]["delivery_id"])

    if request.user.is_authenticated:
        user_id = request.user.id

        order = Order.objects.create(
            user_id=user_id,
            full_name=body['fullname'],
            email=body['email'],
            address1=body['address_1'],
            address2=body['address_2'],
            postal_code=body['postalCode'],
            country_code=body['countryCode'],
            total_paid=body['totalPaid'],
            order_key=body['orderId'],
            payment_option="paypal",
            delivery_option=delivery_option,
            billing_status=True,
        )
        order_id = order.pk
    else:
        if 'anonymous_user' in session:
            annony_user = AnonymousUser.objects.create(
                name = session['anonymous_user']['first_name']+' '+session['anonymous_user']['last_name'],
                email = session['anonymous_user']['email'],
                address1 = session['anonymous_user']['street_address'],
                address2 = session['anonymous_user']['other_address'],
                city = session['anonymous_user']['email'],
                phone = session['anonymous_user']['phone_number'],
            )
            annony_user_id = annony_user.id

        order = Order.objects.create(
            anony_user_id=annony_user_id,
            full_name=body['fullname'],
            email=body['email'],
            address1=body['address_1'],
            address2=body['address_2'],
            phone=session['anonymous_user']['phone_number'],
            postal_code=body['postalCode'],
            country_code=body['countryCode'],
            total_paid=body['totalPaid'],
            delivery_option=delivery_option,
            order_key=body['orderId'],
            payment_option="paypal",
            billing_status=True,
        )
        order_id = order.pk
        

    for item in basket:
        OrderItem.objects.create(order_id=order_id, product=item["product"], price=item["price"], quantity=item["qty"])
        product = get_object_or_404(Product, pk=item["product"].id)
        in_stock = product.in_stock
        new_stock = in_stock - item['qty']
        product.in_stock = new_stock
        product.save()

    return JsonResponse("Payment completed!", safe=False)



def payment_successful(request):
    basket = Basket(request)
    basket.clear()
    if 'anonymous_user' in request.session:
        del request.session['anonymous_user']

    form = AnonymousOrderSearchForm()
    return render(request, "checkout/success.html", {'form': form})

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from django.views.generic import View, ListView
from django.core.mail import EmailMessage
from django.conf import settings

from hitcount.views import HitCountDetailView

from .models import *
from .forms import ContactForm


# Create your views here.


def home(request):
    # products = Product.objects.all()
    products = Product.objects.prefetch_related("product_image").filter(is_active=True)
    blogs = BlogPost.objects.filter(is_active=True)[:3]
    featured = products.filter(is_featured=True)
    context = {
        'products': products,
        'blogs': blogs,
        'featured': featured,
        'active': 'active',
    }
    return render(request, 'store/home.html', context)


def categories(request):

    ''' 
    This view is accesible from all pages because it is
    added to the context manager in the settings.py file
    '''

    return {'category': Category.objects.filter(level=0),}


def product_detail(request, product_url):

    '''
    Single product view
    '''

    product = get_object_or_404(Product, product_url=product_url, is_active=True)
    context = {
        'product': product,
    }
    return render(request, 'store/product-details-affiliate.html', context)


def product_category(request, category_slug):
    '''
    View to filter products by category
    consists of mptt queries
    '''
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(
        category__in=Category.objects.get(slug=category_slug).get_descendants(include_self=True)
        )
    context = {
        'products': products,
        'category_name': category,
    }
    return render(request, 'store/shop-list.html', context)


def shopView(request):
    products = Product.objects.filter(is_active=True)
    context = {
        'products': products,
        'name': 'Shop',
        'active_s': 'active'
    }
    return render(request, 'store/shop.html', context)


def searchView(request):
    if request.method == 'POST':
        param = request.POST['search_q']
        
        if param == '':
            messages.info(request, 'Please enter search parameters')
            return HttpResponseRedirect(request.META["HTTP_REFERER"])
        products = Product.objects.filter(
            Q(category__in=Category.objects.filter(name__icontains=param).get_descendants(include_self=True))|Q(product_name__icontains=param)|Q(description__icontains=param)
        ).distinct()
        print(products)
    context = {
        'products': products,
        'name': 'Search results for \'{}\''.format(param)
    }
    return render(request, 'store/shop.html', context)


#blog views
class BlogListView(ListView):
    model=BlogPost
    template_name = 'store/blog.html'

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['blogs'] = self.model.objects.filter(is_active=True).order_by('-created')
        context['side_bar'] = self.model.objects.all().order_by('?')[:3]
        context['page'] = 'Our Blogs'
        return context


class BlogPostDetailView(HitCountDetailView):
    model = BlogPost
    template_name = 'store/blog-details.html'
    count_hit = True
    context_object_name = 'blog'
    
    def get_queryset(self):
        return self.model.objects.filter(slug=self.kwargs['slug'])
    
    def get_context_data(self, **kwargs):
        context = super(BlogPostDetailView, self).get_context_data(**kwargs)
        get_current_id = self.model.objects.filter(slug=self.kwargs['slug']).first()
        context['next'] = self.model.objects.filter(id__gt=get_current_id.pk).first()
        context['previous'] = self.model.objects.filter(id__lt=get_current_id.pk).first()
        context['other'] = self.model.objects.exclude(slug=self.kwargs['slug'])[:3]
        context['blog_cat'] = Category.objects._mptt_filter(
            blog_cats__in=self.model.objects.all().distinct()
        )
        return context
    

class BlogListCategoryView(View):

    def get(self, request, blog_slug):
        blogs = BlogPost.objects.filter(
            category__in=Category.objects.get(slug=blog_slug).get_descendants(include_self=True)
        )
        other = BlogPost.objects.all().order_by('?')[:3]
        context = {
            'blogs': blogs,
            'side_bar': other,
            'page': 'filtered by {} category'.format(blog_slug)
        }
        return render(request, 'store/blog.html', context)
    


#contact page
def contactView(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            data = {
                'name': form.cleaned_data['name'], 
                'email': form.cleaned_data['email'],
                'subject': form.cleaned_data['subject'],
                'message': form.cleaned_data['message'],
            }
            message = '''
            From : {}
            Email: {}
            Subject: {}
            
            Message:
            {}
            '''.format(data['name'], data['email'], data['subject'], data['message'])
            email = EmailMessage(data['subject'], message, data['email'], [settings.EMAIL_RECEIPIENT])
            # EmailThread(email).start()
            email.send(fail_silently=False)
            return render(request, 'nailspar/contacts.html', {'name': data['name']})
    else:
        form = ContactForm()

    about = About.objects.first()
    context ={
        'form': form,
        'about': about,
    }
    return render(request, 'store/contact.html', context)

store/templates/store/blog-details.html
{% extends 'store\base.html' %}
{% load static %} 
{% block content %}
        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <a href="{% url 'store:blog-list' %}">Blogs</a>
                        </li>
                        <li class="active">{{blog.title}}</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="blog-area pt-120 pb-120">
            <div class="container">
                <div class="row flex-row-reverse">
                    <div class="col-lg-9">
                        <div class="blog-details-wrapper">
                            <div class="blog-details-top">
                                <div class="blog-details-img">
                                    <img style="max-height: 600px; max-width: 600px;" class="" alt="" src="{{blog.cover_img.url}}">
                                </div>
                                <div class="blog-details-content">
                                    <div class="blog-meta-2">
                                        <ul>
                                            <li>{{blog.category.name}}</li>
                                            <li>{{blog.created}}</li>
                                        </ul>
                                    </div>
                                    <h1>{{blog.title}}</h1>
                                    <p>{{blog.content|safe}}</p>
                                </div>
                            </div>
                            <div class="dec-img-wrapper">
                                <div class="row">
                                    {% for image in blog.blog_images.all %}
                                    <div class="col-md-6 col-sm-6 col-12">
                                        <div class="dec-img mb-50">
                                            <img style="max-height: 500px;" alt="{{image.alt_text}}" src="{{image.image.url}}">
                                        </div>
                                    </div>
                                    {% endfor %}
                                    
                                </div>
                                <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehendrit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p> -->
                            </div>
                            <div class="tag-share">
                                <div class="dec-tag">
                                    <ul>
                                        <li>by <a href="https://nailedbynana.com">{{blog.author}}</a></li>
                                        <!-- <li><a href="#">interior ,</a></li>
                                        <li><a href="#">outdoor</a></li> -->
                                    </ul>
                                </div>
                                <div class="blog-share">
                                    <span>share :</span>
                                    <div class="share-social">
                                        <ul>
                                            <li>
                                                <a class="facebook" href="#">
                                                    <i class="icon-social-facebook"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="twitter" href="#">
                                                    <i class="icon-social-twitter"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a class="instagram" href="#">
                                                    <i class="icon-social-instagram"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="next-previous-post">
                                {% if next %}
                                <a href="{% url 'store:blog-detail' next.slug %}"> <i class="fa fa-angle-left"></i> prev post</a>
                                {% endif %}
                                {% if previous %}
                                <a href="{% url 'store:blog-detail' previous.slug %}">next post <i class="fa fa-angle-right"></i></a>
                                {% endif %}
                            </div>
                            <!-- <div class="blog-comment-wrapper mt-55">
                                <h4 class="blog-dec-title">comments : 02</h4>
                                <div class="single-comment-wrapper mt-35">
                                    <div class="blog-comment-img">
                                        <img src="{% static 'assets/images/blog/comment-1.jpg' %}" alt="">
                                    </div>
                                    <div class="blog-comment-content">
                                        <h4>Anthony Stephens</h4>
                                        <span>October 14, 2020 </span>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolor magna aliqua. Ut enim ad minim veniam, </p>
                                        <div class="blog-details-btn">
                                            <a href="blog-details.html">read more</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="single-comment-wrapper mt-50 ml-120">
                                    <div class="blog-comment-img">
                                        <img src="{% static 'assets/images/blog/comment-2.jpg' %}" alt="">
                                    </div>
                                    <div class="blog-comment-content">
                                        <h4>DX Joxova</h4>
                                        <span>October 14, 2020 </span>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolor magna aliqua. Ut enim ad minim veniam, </p>
                                        <div class="blog-details-btn">
                                            <a href="blog-details.html">read more</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="blog-reply-wrapper mt-50">
                                <h4 class="blog-dec-title">post a comment</h4>
                                <form class="blog-form" action="#">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="leave-form">
                                                <input type="text" placeholder="Full Name">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="leave-form">
                                                <input type="email" placeholder="Email Address ">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="text-leave">
                                                <textarea placeholder="Message"></textarea>
                                                <input type="submit" value="POST COMMENT">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div> -->
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="sidebar-wrapper sidebar-wrapper-mrg-right">
                            <div class="sidebar-widget mb-40">
                                <h4 class="sidebar-widget-title">Search </h4>
                                <div class="sidebar-search">
                                    <form class="sidebar-search-form" action="#">
                                        <input type="text" placeholder="Search Post">
                                        <button>
                                            <i class="icon-magnifier"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="sidebar-widget shop-sidebar-border mb-35 pt-40">
                                <h4 class="sidebar-widget-title">Categories </h4>
                                <div class="shop-catigory">
                                    <ul>
                                        {% for item in blog_cat %}
                                        <li><a href="">{{item.name}}</a></li>
                                        {% endfor %}
                                        
                                    </ul>
                                </div>
                            </div>
                            <div class="sidebar-widget shop-sidebar-border mb-40 pt-40">
                                <h4 class="sidebar-widget-title">Other Posts </h4>
                                <div class="recent-post">
                                    {% for item in other %}
                                    <div class="single-sidebar-blog">
                                        <div class="sidebar-blog-img">
                                            <a href="{% url 'store:blog-detail' item.slug %}"><img src="{{item.cover_img.url}}" alt="blog image"></a>
                                        </div>
                                        <div class="sidebar-blog-content">
                                            <h5><a href="{% url 'store:blog-detail' item.slug %}">{{item.title}}</a></h5>
                                            <span>{{item.created}}</span>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    
                                </div>
                            </div>
                            <!-- <div class="sidebar-widget shop-sidebar-border mb-40 pt-40">
                                <h4 class="sidebar-widget-title">Archives </h4>
                                <div class="archives-wrap">
                                    <select>
                                        <option>Select Month</option>
                                        <option> January 2020 </option>
                                        <option> December 2018 </option>
                                        <option> November 2018 </option>
                                    </select>
                                </div>
                            </div>
                            <div class="sidebar-widget shop-sidebar-border pt-40">
                                <h4 class="sidebar-widget-title">Popular Tags</h4>
                                <div class="tag-wrap sidebar-widget-tag">
                                    <a href="#">Clothing</a>
                                    <a href="#">Accessories</a>
                                    <a href="#">For Men</a>
                                    <a href="#">Women</a>
                                    <a href="#">Fashion</a>
                                </div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}