accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm

app_name = "accounts"

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', form_class=UserLoginForm, redirect_field_name='accounts:dashboard'), name='accounts-login'),
    path('auth/login/', views.account_login, name='accounts-login'),
    path('auth/register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('activation-sent/', views.activation_sent, name='activation-sent'),
    path('resend-activation/', views.resend_activation, name='resend-activation'),
    path('logout/', views.logoutView, name='logout'),
    #user dashboard
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('profile/edit-details/', views.edit_details, name='edit-details'),
    path('profile/delete/', views.delete_user, name='delete-account'),
    path('profile/confirm-delete/', views.confirm_account_delete, name='delete_confirmation'),
    path('dashboard/settings/', views.settings, name='settings'),
    path('dashboard/orders/', views.orders, name='orders'),
    path('dashboard/download/', views.user_downloads, name='download'),
    #addresses
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    #wishlist
    path('wishlist/add_to_wishlist/<int:id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.users_wishlist, name='wishlist'),
]   

checkout/urls.py
from . import views
from django.urls import path

app_name = "checkout"

urlpatterns = [
    path('delivery-choices/', views.delivery_choices, name='delivery-choices'),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"), 
    path("auth-handler/", views.checkout_handler, name='auth-handler'),
    path("address/checkout/", views.noAuthCheckoutView, name='no-auth-checkout'),
    #payment 
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),

]

ecom_core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('order.urls', namespace='orders')),
    path('dashboard/', include('services.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^download/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('get-order/', views.getOrder, name='get-order'),
    path('track-order/', views.orderTrackingView, name='track-order'),
]

store/urls.py
from . import views
from django.urls import path


app_name = "store"

urlpatterns = [
    #store urls
    path('', views.home, name='home'),
    path('product-detail/<uuid:product_url>/', views.product_detail, name='product-detail'),
    path('shop/', views.shopView, name='shop'),
    path('category/<slug:category_slug>/', views.product_category, name='category-list'),
    path('search/', views.searchView, name='search'),

    #blog urls
    path('blog-list/', views.BlogListView.as_view(), name='blog-list'),
    path('blog/<slug:slug>/', views.BlogPostDetailView.as_view(), name='blog-detail'),
    path('blog/filter=/<slug:blog_slug>', views.BlogListCategoryView.as_view(), name='blog-category-list'),

    #contact
    path('contact/', views.contactView, name='contact'),
]

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
        ("DD", "Digital Delivery"),
    ]

    delivery_name = models.CharField(
        verbose_name=_("delivery_name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 99999999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=10,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_("list order"), help_text=_("Required"), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

checkout/forms.py
from django import forms


class NoAuthCheckoutForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'placeholder':'eg Wongani'})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'placeholder':'eg Tembo'})
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': '', 'placeholder':'eg doe@gmail.com'})
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'placeholder':'eg 088223****'}),
        max_length=10,
    )
    # company_name = forms.CharField(
    #     widget=forms.TextInput(attrs={'class': '','placeholder':'eg Tech IQ'}),
    #     required=False
    # )
    district_or_city = forms.CharField(
        widget=forms.TextInput(attrs={'class': '','placeholder':'eg Lilongwe'})
    )
    street_address = forms.CharField(
        widget=forms.TextInput(attrs={'class': ' mb-4', 'placeholder':'Street name '})
    )
    other_address = forms.CharField(
        widget=forms.TextInput(attrs={'class': '', 'placeholder':'House number'}),
        required=False
    )
    additional_notes = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder':'eg leave at the door', 'rows':2}),
        required=False
    )

checkout/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from order.models import Order, OrderItem, AnonymousUser
from order.forms import AnonymousOrderSearchForm
from store.models import Product
from accounts.models import Address
from basket.basket import Basket

from .models import DeliveryOptions
from .forms import NoAuthCheckoutForm

# Create your views here.

'''
View to output the delivery options
'''
@login_required
def delivery_choices(request):
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    context = {
        "deliveryoptions": deliveryoptions,
    }

    return render(request, "checkout/delivery_choices.html", context)


''' 
This function will fire once a delivery option has been selected 
via AJAX which is implemeted in the cart.html template,
It will then modify the session and add the delivery price to the 
session and return a JSON response to the frontend.
'''
def basket_update_delivery(request):
    basket = Basket(request)
    if request.POST.get("action") == "post":
        delivery_option = int(request.POST.get("deliveryoption"))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = basket.basket_update_delivery(delivery_type.delivery_price)
        session = request.session
        if "purchase" not in request.session:
            session["purchase"] = {
                "delivery_id": delivery_type.id,
            }
        else:
            session["purchase"]["delivery_id"] = delivery_type.id
            session.modified = True
        response = JsonResponse({"total": str(updated_total_price), "delivery_price": str(delivery_type.delivery_price)})
        return response
    

def checkout_handler(request):
    if request.user.is_authenticated:
        return redirect('checkout:delivery_address')
    else:
        return redirect('checkout:no-auth-checkout')


def noAuthCheckoutView(request):
    session = request.session
    if "purchase" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])
    
    if request.method == "POST":
        form = NoAuthCheckoutForm(request.POST) 
        if form.is_valid():
            session['anonymous_user'] = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email'],
                'phone_number': form.cleaned_data['phone_number'],
                'district_or_city': form.cleaned_data['district_or_city'],
                'street_address': form.cleaned_data['street_address'],
                'other_address': form.cleaned_data['other_address'],
                'additional_notes': form.cleaned_data['additional_notes'],
            }
            return redirect('checkout:payment_selection')
    else:
        if 'anonymous_user' in session:
            form = NoAuthCheckoutForm(
                initial={
                    'first_name': session['anonymous_user']['first_name'],
                    'last_name': session['anonymous_user']['last_name'],
                    'email': session['anonymous_user']['email'],
                    'phone_number': session['anonymous_user']['phone_number'],
                    'district_or_city': session['anonymous_user']['district_or_city'],
                    'street_address': session['anonymous_user']['street_address'],
                    'other_address': session['anonymous_user']['other_address'],
                    'additional_notes': session['anonymous_user']['additional_notes'],
                }
            )
        else:   
            form = NoAuthCheckoutForm()
    context = {
        'form': form,
    }
    return render(request, 'checkout/no-auth-checkout.html', context)


@login_required(redirect_field_name='checkout:delivery_address', login_url='accounts:accounts-login')
def delivery_address(request):

    session = request.session
    if "purchase" not in request.session:
        messages.success(request, "Please select delivery option")
        return HttpResponseRedirect(request.META["HTTP_REFERER"])

    addresses = Address.objects.filter(customer=request.user).order_by("-default")
    if not addresses:
        messages.success(request, "Please add an address before you checkout")
        return redirect('accounts:add_address')

    if "address" not in request.session:
        session["address"] = {"address_id": str(addresses[0].id)}
    else:
        session["address"]["address_id"] = str(addresses[0].id)
        session.modified = True
    
    context = {"addresses": addresses}

    return render(request, "checkout/checkout.html", context)


def payment_selection(request):
    address = None
    if request.user.is_authenticated:
        address = Address.objects.filter(customer=request.user).order_by("-default")
        if "address" not in request.session:
            messages.success(request, "Please select address option")
            return HttpResponseRedirect(request.META["HTTP_REFERER"])
    else:
        address = request.session['anonymous_user']

    return render(request, "checkout/payment.html", {"addresses": address})

#pay pal 



def payment_complete(request):
    session = request.session
    body = json.loads(request.body)
    basket = Basket(request)
    delivery_option = get_object_or_404(DeliveryOptions, pk=session["purchase"]["delivery_id"])

    if request.user.is_authenticated:
        user_id = request.user.id

        order = Order.objects.create(
            user_id=user_id,
            full_name=body['fullname'],
            email=body['email'],
            address1=body['address_1'],
            address2=body['address_2'],
            postal_code=body['postalCode'],
            country_code=body['countryCode'],
            total_paid=body['totalPaid'],
            order_key=body['orderId'],
            payment_option="paypal",
            delivery_option=delivery_option,
            billing_status=True,
        )
        order_id = order.pk
    else:
        if 'anonymous_user' in session:
            annony_user = AnonymousUser.objects.create(
                name = session['anonymous_user']['first_name']+' '+session['anonymous_user']['last_name'],
                email = session['anonymous_user']['email'],
                address1 = session['anonymous_user']['street_address'],
                address2 = session['anonymous_user']['other_address'],
                city = session['anonymous_user']['email'],
                phone = session['anonymous_user']['phone_number'],
            )
            annony_user_id = annony_user.id

        order = Order.objects.create(
            anony_user_id=annony_user_id,
            full_name=body['fullname'],
            email=body['email'],
            address1=body['address_1'],
            address2=body['address_2'],
            phone=session['anonymous_user']['phone_number'],
            postal_code=body['postalCode'],
            country_code=body['countryCode'],
            total_paid=body['totalPaid'],
            delivery_option=delivery_option,
            order_key=body['orderId'],
            payment_option="paypal",
            billing_status=True,
        )
        order_id = order.pk
        

    for item in basket:
        OrderItem.objects.create(order_id=order_id, product=item["product"], price=item["price"], quantity=item["qty"])
        product = get_object_or_404(Product, pk=item["product"].id)
        in_stock = product.in_stock
        new_stock = in_stock - item['qty']
        product.in_stock = new_stock
        product.save()

    return JsonResponse("Payment completed!", safe=False)



def payment_successful(request):
    basket = Basket(request)
    basket.clear()
    if 'anonymous_user' in request.session:
        del request.session['anonymous_user']

    form = AnonymousOrderSearchForm()
    return render(request, "checkout/success.html", {'form': form})

checkout/templates/checkout/checkout.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
{% load basket_template_tags %}

        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <a href="{% url 'store:home' %}">Home</a>
                        </li>
                        <li class="active">Checkout </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="checkout-main-area pt-30 pb-30">
            <div class="container">
                <!-- <div class="customer-zone mb-20">
                    <p class="cart-page-title">Returning customer? <a class="checkout-click1" href="#">Click here to login</a></p>
                    <div class="checkout-login-info">
                        <p>If you have shopped with us before, please enter your details in the boxes below. If you are a new customer, please proceed to the Billing & Shipping section.</p>
                        <form action="#">
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="sin-checkout-login">
                                        <label>Username or email address <span>*</span></label>
                                        <input type="text" name="user-name">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="sin-checkout-login">
                                        <label>Passwords <span>*</span></label>
                                        <input type="password" name="user-password">
                                    </div>
                                </div>
                            </div>
                            <div class="button-remember-wrap">
                                <button class="button" type="submit">Login</button>
                                <div class="checkout-login-toggle-btn">
                                    <input type="checkbox">
                                    <label>Remember me</label>
                                </div>
                            </div>
                            <div class="lost-password">
                                <a href="#">Lost your password?</a>
                            </div>
                        </form>
                        <div class="checkout-login-social">
                            <span>Login with:</span>
                            <ul>
                                <li><a href="#">Facebook</a></li>
                                <li><a href="#">Twitter</a></li>
                                <li><a href="#">Google</a></li>
                            </ul>
                        </div>
                    </div>
                </div> -->
                <div class="customer-zone mb-20">
                    <p class="cart-page-title">Have a coupon? <a class="checkout-click3" href="#">Click here to enter your code</a></p>
                    <div class="checkout-login-info3">
                        <form action="#">
                            <input type="text" placeholder="Coupon code">
                            <input type="submit" value="Apply Coupon">
                        </form>
                    </div>
                </div>
                <div class="checkout-wrap pt-30">
                    <div class="row">
                        <div class="col-lg-7">
                            
                            <div class="myaccount-content">
                                <h3>Add Address</h3>
                                <a href="{% url 'accounts:add_address' %}">Add Address</a>
                                <hr>
                                
                               
                                <h3>Select Your Billing Address<small>(or proceed with your default address)</small></h3>
                                {% for item in addresses %}
                                <div data-index="{{item.id}}">
                                    {% if not item.default %}
                                    <p>other addresses</p>
                                    {% endif %}
                                    {% if item.default %}
                                    <h3>Selected</h3>
                                    {% endif %}
                                    <address>
                                        <p><strong>{{item.full_name}}</strong></p>
                                        <p>{{item.address_line}}<br>
                                    {{item.address_line2}}</p>
                                        <p>{{ item.town_city}}</p>
                                        <p>{{ item.postcode}}</p>
                                        <p>Mobile:{{item.phone}}</p>
                                    </address>
                                
                                    <a href="{% url 'accounts:edit_address' item.id%}" class="check-btn sqr-btn "><i class="fa fa-edit"></i> Edit Address</a> 
                                    {% if not item.default %}     
                                    | <a href="{% url 'accounts:set_default' item.id%}" class="check-btn sqr-btn "><i class="fa fa-edit"></i>Select </a>
                                    {% endif %}
                                    <hr>
                                    
                                </div>
                                {% endfor %}
                                <h3><a href="{% url 'checkout:payment_selection' %}">Proceed To Payment</a></h3>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <!-- <div class="your-order-area">
                                <h3>Your order</h3>
                                <div class="your-order-wrap gray-bg-4">
                                    <div class="your-order-info-wrap">
                                        <div class="your-order-info">
                                            <ul>
                                                <li>Product <span>Total</span></li>
                                            </ul>
                                        </div>
                                        <div class="your-order-middle">
                                            <ul>
                                                <li>Product Name X 1 <span>$329 </span></li>
                                                <li>Product Name X 1 <span>$329 </span></li>
                                            </ul>
                                        </div>
                                        <div class="your-order-info order-subtotal">
                                            <ul>
                                                <li>Subtotal <span>$329 </span></li>
                                            </ul>
                                        </div>
                                        <div class="your-order-info order-shipping">
                                            <ul>
                                                <li>Shipping <p>Enter your full address </p>
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="your-order-info order-total">
                                            <ul>
                                                <li>Total <span>$273.00 </span></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="payment-method">
                                        <div class="pay-top sin-payment">
                                            <input id="payment_method_1" class="input-radio" type="radio" value="cheque" checked="checked" name="payment_method">
                                            <label for="payment_method_1"> Direct Bank Transfer </label>
                                            <div class="payment-box payment_method_bacs">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference.</p>
                                            </div>
                                        </div>
                                        <div class="pay-top sin-payment">
                                            <input id="payment-method-2" class="input-radio" type="radio" value="cheque" name="payment_method">
                                            <label for="payment-method-2">Check payments</label>
                                            <div class="payment-box payment_method_bacs">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference.</p>
                                            </div>
                                        </div>
                                        <div class="pay-top sin-payment">
                                            <input id="payment-method-3" class="input-radio" type="radio" value="cheque" name="payment_method">
                                            <label for="payment-method-3">Cash on delivery </label>
                                            <div class="payment-box payment_method_bacs">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference.</p>
                                            </div>
                                        </div>
                                        <div class="pay-top sin-payment sin-payment-3">
                                            <input id="payment-method-4" class="input-radio" type="radio" value="cheque" name="payment_method">
                                            <label for="payment-method-4">PayPal <img alt="" src="assets/images/icon-img/payment.png"><a href="#">What is PayPal?</a></label>
                                            <div class="payment-box payment_method_bacs">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="Place-order">
                                    <a href="#">Place Order</a>
                                </div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="subscribe-area bg-gray pt-115 pb-115">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-5">
                        <div class="section-title">
                            <h2>keep connected</h2>
                            <p>Get updates by subscribe our weekly newsletter</p>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7">
                        <div id="mc_embed_signup" class="subscribe-form">
                            <form id="mc-embedded-subscribe-form" class="validate subscribe-form-style" novalidate="" target="_blank" name="mc-embedded-subscribe-form" method="post" action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef">
                                <div id="mc_embed_signup_scroll" class="mc-form">
                                    <input class="email" type="email" required="" placeholder="Enter your email address" name="EMAIL" value="">
                                    <div class="mc-news" aria-hidden="true">
                                        <input type="text" value="" tabindex="-1" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef">
                                    </div>
                                    <div class="clear">
                                        <input id="mc-embedded-subscribe" class="button" type="submit" name="subscribe" value="Subscribe">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}