accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm

app_name = "accounts"

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', form_class=UserLoginForm, redirect_field_name='accounts:dashboard'), name='accounts-login'),
    path('auth/login/', views.account_login, name='accounts-login'),
    path('auth/register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('activation-sent/', views.activation_sent, name='activation-sent'),
    path('resend-activation/', views.resend_activation, name='resend-activation'),
    path('logout/', views.logoutView, name='logout'),
    #user dashboard
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('profile/edit-details/', views.edit_details, name='edit-details'),
    path('profile/delete/', views.delete_user, name='delete-account'),
    path('profile/confirm-delete/', views.confirm_account_delete, name='delete_confirmation'),
    path('dashboard/settings/', views.settings, name='settings'),
    path('dashboard/orders/', views.orders, name='orders'),
    path('dashboard/download/', views.user_downloads, name='download'),
    #addresses
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    #wishlist
    path('wishlist/add_to_wishlist/<int:id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.users_wishlist, name='wishlist'),
]   

ecom_core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('order.urls', namespace='orders')),
    path('dashboard/', include('services.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^download/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('get-order/', views.getOrder, name='get-order'),
    path('track-order/', views.orderTrackingView, name='track-order'),
]

store/urls.py
from . import views
from django.urls import path


app_name = "store"

urlpatterns = [
    #store urls
    path('', views.home, name='home'),
    path('product-detail/<uuid:product_url>/', views.product_detail, name='product-detail'),
    path('shop/', views.shopView, name='shop'),
    path('category/<slug:category_slug>/', views.product_category, name='category-list'),
    path('search/', views.searchView, name='search'),

    #blog urls
    path('blog-list/', views.BlogListView.as_view(), name='blog-list'),
    path('blog/<slug:slug>/', views.BlogPostDetailView.as_view(), name='blog-detail'),
    path('blog/filter=/<slug:blog_slug>', views.BlogListCategoryView.as_view(), name='blog-category-list'),

    #contact
    path('contact/', views.contactView, name='contact'),
]

order/forms.py
from django import forms


class AnonymousOrderSearchForm(forms.Form):
    order_email = forms.EmailField(
        widget=forms.EmailInput(attrs={'name':'order_email', 'placeholder':'Email you used during checkout'}),
        required=True
    )
    order_key = forms.CharField(
        widget=forms.TextInput(attrs={'name': 'order_key ', 'placeholder':'Found in your order confirmation email.'})
    )

accounts/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.utils.encoding import force_bytes, force_str #force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages
from django.urls import reverse
from django.conf import settings

from .token import account_activation_token
from .models import Customer, Address, UserToken
from .mixins import auth_user_should_not_access
from .forms import UserRegistrationForm, UserEditForm, UserAddressForm, UserLoginForm

from store.models import Product
from order.models import Order


# Create your views here.

@auth_user_should_not_access
def account_login(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if user is not None and user.is_active:
                auth_login(request, user)
                return redirect('accounts:dashboard') 
            else:
                # if user.is_active==False:
                #     messages.error(request, 'Account does not exist') 
                #     return HttpResponseRedirect(request.META["HTTP_REFERER"])
                messages.warning(request, 'Invalid credentials')
                return HttpResponseRedirect(request.META["HTTP_REFERER"])
        else:
            messages.warning(request, 'Invalid form data')
            return HttpResponseRedirect(request.META["HTTP_REFERER"])
    else:
        form = UserLoginForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@auth_user_should_not_access
def account_register(request):
    
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == "POST":
        register_form = UserRegistrationForm(request.POST)
        if register_form.is_valid():
            user = register_form.save(commit=False)
            user.email = register_form.cleaned_data['email']
            user.set_password(register_form.cleaned_data['password'])
            user.is_active = False
            user.save()
            request.session['user_id'] = user.id
            
            #setup email
            user_token = account_activation_token.make_token(user)
            user_uid = urlsafe_base64_encode(force_bytes(user.pk))
            current_site = get_current_site(request)
            subject = "Activate your account"
            message = render_to_string('accounts/account-activation-email.html', {
                'user': user,
                'domain': current_site,
                'uid': user_uid,
                'token': user_token,
            })
            user.email_user(subject=subject, message=message)
            store_user_token = UserToken.objects.create(
                user=user,
                uid=user_uid,
                token=user_token,
            )
            return redirect('accounts:activation-sent')
    
    else:
        register_form = UserRegistrationForm()
    
    return render(request, 'accounts/login-register.html', {'form': register_form})


@auth_user_should_not_access
def activation_sent(request):

    return render(request, 'accounts/resend-code.html')


@auth_user_should_not_access
def resend_activation(request):
    pk = request.session['user_id']
    user = get_object_or_404(Customer, pk=pk)
    token = get_object_or_404(UserToken, user=user)
    user_token = token.token
    user_uid = token.uid
    current_site = get_current_site(request)
    subject = "Activate your account"
    message = render_to_string('accounts/account-activation-email.html', {
        'user': user,
        'domain': current_site,
        'uid': user_uid,
        'token': user_token,
    })
    user.email_user(subject=subject, message=message)
    return redirect(reverse('accounts:activation-sent'))


@auth_user_should_not_access
def account_activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Customer.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
        pass
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        messages.info(request, 'Account Activated successfully')
        if 'user_id' in request.session:
            del request.session['user_id']
        return redirect('accounts:dashboard')
    else:
        return render(request, 'accounts/activation-invalid.html')


def logoutView(request):
    logout(request)
    messages.info(request, 'You have successfully logged out')
    return redirect(reverse('store:home'))


#dashboard section
@login_required
def user_dashboard(request):
    context = {

    }
    return render(request, 'accounts/my-account.html', context)


@login_required(login_url='accounts:accounts-login')
def edit_details(request):
    user = request.user
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, f'Your account has been updated')
            return redirect('accounts:edit-details')
    else:
        user_form = UserEditForm(instance=request.user)

    return render(request, 'accounts/edit-details.html', {'user_form': user_form, 'user': user})


@login_required(login_url='accounts:accounts-login')
def orders(request):
    user_id = request.user.id
    orders = Order.objects.filter(user_id=user_id).filter(billing_status=True)
    context = {
        'orders': orders,
    }
    return render(request, 'accounts/orders.html', context)


def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open (file_path, 'rb')as fh:
            response = HttpResponse(fh.read(), content_type="application/digital_product")
            response['Content-Desposition']='inline;filename='+os.path.basename(file_path)
            return response
    raise Http404


@login_required(login_url='accounts:accounts-login')
def user_downloads(request):
    user_id = request.user.id
    orders = Order.objects.filter(user_id=user_id).filter(billing_status=True)
    context = {
        'orders': orders,
    }
    return render(request, 'accounts/download.html', context)


@login_required(login_url='accounts:accounts-login')
def settings(request):
    return render(request, 'accounts/settings.html')


@login_required(login_url='accounts:accounts-login')
def delete_user(request):
    user = Customer.objects.get(user_name=request.user)
    user.is_active = False
    user.save()
    logout(request)
    return redirect('accounts:delete_confirmation')

def confirm_account_delete(request):
    return render(request, 'accounts/delete-confirmation.html')

#address section
@login_required(login_url='accounts:accounts-login')
def view_address(request):
    addresses = Address.objects.filter(customer=request.user)
    context = {
        'addresses': addresses,
    }
    return render(request, 'accounts/view-address.html', context)


@login_required(login_url='accounts:accounts-login')
def add_address(request):
    if request.method=='POST':
        address_form = UserAddressForm(data=request.POST)
        if address_form.is_valid():
            address_form = address_form.save(commit=False)
            address_form.customer = request.user
            address_form.save()
            return HttpResponseRedirect(reverse('accounts:addresses'))
    else:
        address_form = UserAddressForm()
        
    return render(request, 'accounts/add-address.html', {'form': address_form})


@login_required(login_url='accounts:accounts-login')
def edit_address(request, id):

    if request.method == "POST":
        address = Address.objects.get(pk=id, customer=request.user)
        address_form = UserAddressForm(instance=address, data=request.POST)
        if address_form.is_valid():
            address_form.save()
            return HttpResponseRedirect(reverse("accounts:addresses"))
    else:
        address = Address.objects.get(pk=id, customer=request.user)
        address_form = UserAddressForm(instance=address)

    return render(request, 'accounts/edit-address.html', {"form": address_form})


@login_required(login_url='accounts:accounts-login')
def delete_address(request, id):
    address = Address.objects.filter(pk=id, customer=request.user).delete()
    return redirect("accounts:addresses")


@login_required(login_url='accounts:accounts-login')
def set_default(request, id):
    Address.objects.filter(customer=request.user, default=True).update(default=False)
    Address.objects.filter(pk=id, customer=request.user).update(default=True)

    previous_url = request.META.get("HTTP_REFERER")

    if "delivery_address" in previous_url:
        return redirect("checkout:delivery_address")

    return redirect("accounts:addresses")   

#whislist section

@login_required(login_url='accounts:accounts-login')
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
        messages.success(request, product.title + " has been removed from your WishList")
    else:

order/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_list_or_404
from django.db.models import Q

from basket.basket import Basket

from .models import Order, OrderItem
from .forms import AnonymousOrderSearchForm


def getOrder(request):
    # q = None
    form = AnonymousOrderSearchForm()
    if request.method == 'POST':
        form = AnonymousOrderSearchForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['order_email']
            order_key = form.cleaned_data['order_key']
            try:
                order = get_list_or_404(Order, email=email, order_key=order_key)
            except:
                context = {'form':form,}
                return render(request, 'order/order-not-found.html', context)     
    context = {
        'order': order,
    }
    return render(request, 'order/my-account.html', context)


def orderTrackingView(request):
    form = AnonymousOrderSearchForm()
    if request.method == 'POST':
        form = AnonymousOrderSearchForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['order_email']
            order_key = form.cleaned_data['order_key']
            try:
                order = get_list_or_404(Order, email=email, order_key=order_key)
                return render(request, 'order/my-account.html', context={'order': order,})
            except:
                context = {'form':form,}
                return render(request, 'order/order-not-found.html', context)     
    context = {
        'form':form,
    }
    return render(request, 'order/order-tracking.html', context)

accounts/templates/accounts/account-activation-email.html
{% autoescape off %}
Hi {{user.user_name}}

Your account has successfully been created. 
Please click the link below to activate your account 

{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

{% endautoescape %}

accounts/templates/accounts/dashboard-nav.html
{% load static %}
<div class="col-lg-3 col-md-4">
    <div class="myaccount-tab-menu nav" role="tablist">
        <a href="{% url 'accounts:dashboard' %}"  ><i class="fa fa-dashboard"></i>
            Dashboard</a>
        <a href="{% url 'accounts:orders' %}" ><i class="fa fa-cart-arrow-down"></i> Orders</a>
        <a href="{% url 'accounts:download' %}" ><i class="fa fa-cloud-download"></i> Download</a>
        <a href="#payment-method" ><i class="fa fa-credit-card"></i> Payment
            Method</a>
        <a href="{% url 'accounts:addresses' %}" ><i class="fa fa-map-marker"></i> address</a>
        <a href="{% url 'accounts:edit-details' %}"  ><i class="fa fa-user"></i> Account Details</a>
        <a href="{% url 'accounts:settings' %}" ><i class="fa fa-map-marker"></i> Settings</a>
        <a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
    </div>
</div>
<!-- class="active" -->

accounts/templates/accounts/delete-confirmation.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <h3>Account deleted</h3>
                        </li>
                        <!-- <li class="active">Account Deleted</li> -->
                    </ul>
                </div>
            </div>
        </div>
        <!-- order tracking start -->
        <div class="order-tracking-area pt-110 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-8 col-md-10 ml-auto mr-auto">
                        <div class="order-tracking-content">
                            <p>Your account has been successfully deleted. Thank you for using our service.</p>
                            <div class="order-track-btn">
                                <!-- <a href="{% url 'store:home' %}">Home</a> -->
                            </div>
                            <!-- <div class="order-tracking-form">
                                <form action="#">
                                    <div class="sin-order-tracking">
                                        <label>Order ID</label>
                                        <input type="text" placeholder="Found in your order confirmation email.">
                                    </div>
                                    <div class="sin-order-tracking">
                                        <label>Billing Email</label>
                                        <input type="email" placeholder="Email you used during checkout">
                                    </div>
                                    <div class="order-track-btn">
                                        <a href="#">Track Now</a>
                                    </div>
                                </form>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

accounts/templates/accounts/settings.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <a href="index.html">Home</a>
                        </li>
                        <li class="active">my account </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- my account wrapper start -->
        <div class="my-account-wrapper pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- My Account Page Start -->
                        <div class="myaccount-page-wrapper">
                            <!-- My Account Tab Menu Start -->
                            <div class="row">
                                {% include 'accounts/dashboard-nav.html' %}
                                <!-- My Account Tab Menu End -->
                                <!-- My Account Tab Content Start -->
                                <div class="col-lg-9 col-md-8">
                                    <div class="tab-content" id="myaccountContent">
                                                                               
                                    
                                        <!-- Single Tab Content Start -->
                                        <div class="tab-pane fade show active" id="address-edit" role="tabpanel">
                                            <div class="myaccount-content">
                                                <h3>Settings</h3>
                                                <address>
                                                    <p><strong>Alex Tuntuni</strong></p>
                                                    <p>1355 Market St, Suite 900 <br>
                                                San Francisco, CA 94103</p>
                                                    <p>Mobile: (123) 456-7890</p>
                                                </address>
                                                <!-- <a href="{% url 'accounts:settings' %}" class="check-btn sqr-btn "><i class="fa fa-edit"></i> Edit Address</a> -->
                                                <!-- <form method="post" action="{% url 'accounts:delete-account' %}">
                                                    <p>Are you sure you want to delete your account?</p>
                                                    <br>
                                                    <button >Delete Account</button>
                                                </form> -->
                                                <div class="order-track-btn">
                                                    <a href="{% url 'accounts:delete-account' %}">Delete Account</a>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Single Tab Content End -->

                                    </div>
                                </div> <!-- My Account Tab Content End -->
                            </div>
                        </div> <!-- My Account Page End -->
                    </div>
                </div>
            </div>
        </div>
        <!-- my account wrapper end -->
        <div class="subscribe-area bg-gray pt-115 pb-115">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-5">
                        <div class="section-title">
                            <h2>keep connected</h2>
                            <p>Get updates by subscribe our weekly newsletter</p>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7">
                        <div id="mc_embed_signup" class="subscribe-form">
                            <form id="mc-embedded-subscribe-form" class="validate subscribe-form-style" novalidate="" target="_blank" name="mc-embedded-subscribe-form" method="post" action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef">
                                <div id="mc_embed_signup_scroll" class="mc-form">
                                    <input class="email" type="email" required="" placeholder="Enter your email address" name="EMAIL" value="">
                                    <div class="mc-news" aria-hidden="true">
                                        <input type="text" value="" tabindex="-1" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef">
                                    </div>
                                    <div class="clear">
                                        <input id="mc-embedded-subscribe" class="button" type="submit" name="subscribe" value="Subscribe">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

accounts/templates/accounts/wishlist.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <a href="{% url 'store:home' %}">Home</a>
                        </li>
                        <li class="active">Wishlist </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="cart-main-area pt-60 pb-60">
            <div class="container">
                <h3 class="cart-page-title">Your wishlist items</h3>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <form action="#">
                            <div class="table-content table-responsive cart-table-content">
                                <table>
                                    {% if wishlist %}
                                    <thead> 
                                        <tr>
                                            <th>Image</th>
                                            <th>Product Name</th>
                                            <th>Until Price</th>
                                            <!-- <th>Qty</th>
                                            <th>Subtotal</th> -->
                                            <th>action</th>
                                        </tr>
                                    </thead>
                                    {% endif %}
                                    <tbody>
                                        {% for item in wishlist %}
                                        <tr>
                                            <td class="product-thumbnail">
                                                <a href="{% url 'store:product-detail' item.id %}">
                                                    {% for image in item.product_image.all %}
                                                        {% if image.is_feature %}
                                                            <img style="max-height: 100px;" src="{{image.image.url}}" alt="{{image.alt_text}}">
                                                        {% endif %}
                                                    {% endfor %}
                                                </a>
                                            </td>
                                            <td class="product-name"><a href="{% url 'store:product-detail' item.id %}">{{item.product_name}}</a></td>
                                            <td class="product-price-cart"><span class="amount">${{ item.regular_price }}</span></td>
                                            <!-- <td class="product-quantity pro-details-quality">
                                                <div class="cart-plus-minus">
                                                    <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1">
                                                </div>
                                            </td>
                                            <td class="product-subtotal">$110.00</td> -->
                                            <td class="product-wishlist-cart">
                                                <a href="{% url 'accounts:add_to_wishlist' item.id %}">Remove </a>
                                            </td>
                                        </tr>
                                        {% empty %}
                                        <h2>You have not added products to your wishlist</h2>
                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="subscribe-area bg-gray pt-115 pb-115">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-5">
                        <div class="section-title">
                            <h2>keep connected</h2>
                            <p>Get updates by subscribe our weekly newsletter</p>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-7">
                        <div id="mc_embed_signup" class="subscribe-form">
                            <form id="mc-embedded-subscribe-form" class="validate subscribe-form-style" novalidate="" target="_blank" name="mc-embedded-subscribe-form" method="post" action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef">
                                <div id="mc_embed_signup_scroll" class="mc-form">
                                    <input class="email" type="email" required="" placeholder="Enter your email address" name="EMAIL" value="">
                                    <div class="mc-news" aria-hidden="true">
                                        <input type="text" value="" tabindex="-1" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef">
                                    </div>
                                    <div class="clear">
                                        <input id="mc-embedded-subscribe" class="button" type="submit" name="subscribe" value="Subscribe">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       {% endblock %}