ecom_core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('orders/', include('order.urls', namespace='orders')),
    path('dashboard/', include('services.dashboard.urls', namespace='dashboard')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^download/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('get-order/', views.getOrder, name='get-order'),
    path('track-order/', views.orderTrackingView, name='track-order'),
]

services/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('store-dashboard/', views.ordersDashboard, name='orders-dashboard'),
]

store/urls.py
from . import views
from django.urls import path


app_name = "store"

urlpatterns = [
    #store urls
    path('', views.home, name='home'),
    path('product-detail/<uuid:product_url>/', views.product_detail, name='product-detail'),
    path('shop/', views.shopView, name='shop'),
    path('category/<slug:category_slug>/', views.product_category, name='category-list'),
    path('search/', views.searchView, name='search'),

    #blog urls
    path('blog-list/', views.BlogListView.as_view(), name='blog-list'),
    path('blog/<slug:slug>/', views.BlogPostDetailView.as_view(), name='blog-detail'),
    path('blog/filter=/<slug:blog_slug>', views.BlogListCategoryView.as_view(), name='blog-category-list'),

    #contact
    path('contact/', views.contactView, name='contact'),
]

order/models.py
from decimal import Decimal
import uuid

from django.conf import settings
from django.db import models

from store.models import Product
from checkout.models import DeliveryOptions

# Create your models here.


class AnonymousUser(models.Model):
    name = models.CharField(max_length=255, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    email = models.EmailField(max_length=255, blank=True)
    address1 = models.CharField(max_length=250, null=True)
    address2 = models.CharField(max_length=250, null=True)
    city = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=100, null=True)
    postal_code = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Recieved', 'Recieved'),
        ('On Delivery', 'On Delivery'),
        ('Delivered', 'Delivered'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name='order_user')
    anony_user = models.ForeignKey(AnonymousUser,
        on_delete=models.CASCADE,
        null=True, 
        blank=True, 
        related_name='anony_user_order')
    full_name = models.CharField(max_length=50, null=True)
    email = models.EmailField(max_length=255, blank=True)
    address1 = models.CharField(max_length=250, null=True)
    address2 = models.CharField(max_length=250, null=True)
    city = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=100, null=True)
    postal_code = models.CharField(max_length=20, null=True)
    country_code =models.CharField(max_length=4, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    total_paid = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    order_key = models.CharField(max_length=200, null=True)
    payment_option = models.CharField(max_length=255, blank=True, null=True)
    billing_status = models.BooleanField(default=False, null=True)
    order_status = models.CharField(max_length=300, null=True, choices=STATUS, default='Pending')
    additional_text = models.TextField(null=True, blank=True)
    delivery_option = models.ForeignKey(DeliveryOptions, null=True, on_delete=models.DO_NOTHING, related_name='d_option')

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return 'Order for {}'.format(self.full_name) 


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return 'order items for {}-{}'.format(self.order.full_name, self.product.product_name)

order/forms.py
from django import forms


class AnonymousOrderSearchForm(forms.Form):
    order_email = forms.EmailField(
        widget=forms.EmailInput(attrs={'name':'order_email', 'placeholder':'Email you used during checkout'}),
        required=True
    )
    order_key = forms.CharField(
        widget=forms.TextInput(attrs={'name': 'order_key ', 'placeholder':'Found in your order confirmation email.'})
    )

order/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_list_or_404
from django.db.models import Q

from basket.basket import Basket

from .models import Order, OrderItem
from .forms import AnonymousOrderSearchForm


def getOrder(request):
    # q = None
    form = AnonymousOrderSearchForm()
    if request.method == 'POST':
        form = AnonymousOrderSearchForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['order_email']
            order_key = form.cleaned_data['order_key']
            try:
                order = get_list_or_404(Order, email=email, order_key=order_key)
            except:
                context = {'form':form,}
                return render(request, 'order/order-not-found.html', context)     
    context = {
        'order': order,
    }
    return render(request, 'order/my-account.html', context)


def orderTrackingView(request):
    form = AnonymousOrderSearchForm()
    if request.method == 'POST':
        form = AnonymousOrderSearchForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['order_email']
            order_key = form.cleaned_data['order_key']
            try:
                order = get_list_or_404(Order, email=email, order_key=order_key)
                return render(request, 'order/my-account.html', context={'order': order,})
            except:
                context = {'form':form,}
                return render(request, 'order/order-not-found.html', context)     
    context = {
        'form':form,
    }
    return render(request, 'order/order-tracking.html', context)

order/templates/order/my-account.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <a href="{% url 'store:shop' %}">store</a>
                        </li>
                        <li class="active">my order</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- my account wrapper start -->
        <div class="my-account-wrapper pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- My Account Page Start -->
                        <div class="myaccount-page-wrapper">
                            <!-- My Account Tab Menu Start -->
                            <div class="row">
                                <div class="col-lg-3 col-md-4">
                                    <div class="myaccount-tab-menu nav" role="tablist">
                                        <a href="#orders" class="active" data-toggle="tab"><i class="fa fa-dashboard"></i>
                                            Order Details</a>
                                        <a href="#ordersitems" data-toggle="tab"><i class="fa fa-cart-arrow-down"></i> Order Items</a>
                                        <!-- <a href="#download" data-toggle="tab"><i class="fa fa-cloud-download"></i> Download</a>
                                        <a href="#payment-method" data-toggle="tab"><i class="fa fa-credit-card"></i> Payment
                                            Method</a>
                                        <a href="#address-edit" data-toggle="tab"><i class="fa fa-map-marker"></i> address</a>
                                        <a href="#account-info" data-toggle="tab"><i class="fa fa-user"></i> Account Details</a>
                                        <a href="login-register.html"><i class="fa fa-sign-out"></i> Logout</a> -->
                                    </div>
                                </div>
                                <!-- My Account Tab Menu End -->
                                <!-- My Account Tab Content Start -->
                                <div class="col-lg-9 col-md-8">
                                    <div class="tab-content" id="myaccountContent">
                                        <!-- Single Tab Content Start -->
                                        <div class="tab-pane fade show active" id="orders" role="tabpanel">
                                            <div class="myaccount-content">
                                                <h3>Billing and Order Detials</h3>
                                                {% for i in order %}
                                                <address>
                                                    <p><strong>{{i.anony_user.name}}</strong></p>
                                                    <p>{{i.email}}, {{i.address1}} <br>
                                                {{i.address2}}, {{i.city}}</p>
                                                    <p>Mobile: {{i.anony_user.phone}}</p>
                                                </address>
                                                <p>Total Paid: {{i.total_paid}}</p>
                                                <p>Order Key: {{i.order_key}}</p>
                                                <p>created on: {{i.created}}</p>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <!-- Single Tab Content End -->
                                        <!-- Single Tab Content Start -->
                                        <div class="tab-pane fade" id="ordersitems" role="tabpanel">
                                            <div class="myaccount-content">
                                                <h3>Ordered Products</h3>
                                                <div class="myaccount-table table-responsive text-center">
                                                    <table class="table table-bordered">
                                                        <thead class="thead-light">
                                                            <tr>
                                                                <th>Order</th>
                                                                <th>Product Name</th>
                                                                <th>Status</th>
                                                                <th>Price</th>
                                                                <th>Quanitity</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for order in order %}
                                                            {% for i in order.items.all %}
                                                                <tr>
                                                                    <td>1</td>
                                                                    <td>{{i.product.product_name}}</td>
                                                                    <td>{{order.order_status}}</td>
                                                                    <td>MWK {{i.price}}</td>
                                                                    <td>{{i.quantity}}</td>
                                                                </tr>
                                                            {% endfor %}
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Single Tab Content End -->
                                    </div>
                                </div> <!-- My Account Tab Content End -->
                            </div>
                        </div> <!-- My Account Page End -->
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

order/templates/order/order-not-found.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <h3>Order Not Found</h3>
                        </li>
                        <!-- <li class="active">Account Deleted</li> -->
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="order-tracking-area pt-110 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-8 col-md-10 ml-auto mr-auto">
                        <div class="order-tracking-content">
                            <h3>No order with the entered details was found
                            </h3>
                            <p>Please try to enter the order details again!</p>
                            <div class="order-track-btn">
                                <!-- <a href="{% url 'accounts:dashboard' %}">View Dashboard</a> -->
                            </div>
                            <div class="order-tracking-form">
                                <form method="post" action="{% url 'orders:get-order' %}">
                                    {% csrf_token %}
                                    <div class="sin-order-tracking">
                                        <label>Order ID</label>
                                        <!-- <input type="text" placeholder="Found in your order confirmation email."> -->
                                        {{form.order_key}}
                                        {{form.order_key.errors}}
                                    </div>
                                    <div class="sin-order-tracking">
                                        <label>Billing Email</label>
                                        <!-- <input type="email" placeholder="Email you used during checkout">
                                         -->
                                        {{form.order_email}}
                                        {{form.order_email.errors}}
                                    </div>
                                    <div class="order-track-btn">
                                        <button class="btn btn-dark w-100" type="submit">View Receipt</button>
                                    </div>
                                    
                                </form>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

order/templates/order/order-tracking.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

        <div class="breadcrumb-area bg-gray">
            <div class="container">
                <div class="breadcrumb-content text-center">
                    <ul>
                        <li>
                            <h3>Track Your Order</h3>
                        </li>
                        <!-- <li class="active">Account Deleted</li> -->
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="order-tracking-area pt-110 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-8 col-md-10 ml-auto mr-auto">
                        <div class="order-tracking-content">
                            <h3>To Track your order please enter the follwing details
                            </h3>
                            <div class="order-tracking-form">
                                <form method="post" action="{% url 'orders:track-order' %}">
                                    {% csrf_token %}
                                    
                                    <div class="sin-order-tracking">
                                        <label>Order ID</label>
                                        <!-- <input type="text" placeholder="Found in your order confirmation email."> -->
                                        {{form.order_key}}
                                        {{form.order_key.errors}}
                                    </div>
                                    <div class="sin-order-tracking">
                                        <label>Billing Email</label>
                                        <!-- <input type="email" placeholder="Email you used during checkout">
                                         -->
                                        {{form.order_email}}
                                        {{form.order_email.errors}}
                                    </div>
                                    <div class="order-track-btn">
                                        <button class="btn btn-dark w-100" type="submit">View Receipt</button>
                                    </div>
                                </form>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}